# Generated by Django 5.2.17 on 2026-10-02 21:31

import django.core.validators
from django.db import migrations, models


# The labels every installation starts with. More can be added in the app.
DEFAULT_LABELS = [
    ('At risk', '#c62828'),
    ('Requires follow up', '#e65100'),
    ('Defaulting', '#000000'),
]


def create_default_labels(apps, schema_editor):
    Label = apps.get_model('api', 'Label')
    for name, color in DEFAULT_LABELS:
        Label.objects.get_or_create(name=name, defaults={'color': color})


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pms_identifiers_and_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a colour in the form #rrggbb.')])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='ledger_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='removed_from_pms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tenants', to='api.label'),
        ),
        migrations.RunPython(create_default_labels, migrations.RunPython.noop),
    ]
