# Generated by Django 6.1.1 on 2026-10-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pms_identifiers_and_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='ledger_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='removed_from_pms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pms_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
