# Generated by Django 5.2.17 on 2026-10-02 21:42

from django.db import migrations, models


def categorize_existing(apps, schema_editor):
    # The rule in api/services/categories.py as it stood when this migration
    # was written, copied here so the migration never changes behaviour when
    # that code does.
    Transaction = apps.get_model('api', 'Transaction')
    Transaction.objects.filter(description__icontains='security deposit').update(category='deposit')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sync_tracking_and_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('rent_and_fees', 'Rent and fees'), ('deposit', 'Security deposit')], default='rent_and_fees', max_length=16),
        ),
        migrations.RunPython(categorize_existing, migrations.RunPython.noop),
    ]
